apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jts3servermod.fullname" . }}
  labels:
    {{- include "jts3servermod.labels" . | nindent 4 }}
data:
  JTS3ServerMod_InstanceManager.cfg: |- {{ .Values.jts3servermod.instanceManagerCfg | nindent 4 }}
